sso_admin_role:
  arn: arn:aws:iam::728882028485:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_Administrator_3a9d61d0884be260
sso_viewer_role:
  arn: arn:aws:iam::728882028485:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_Viewer_e90b0168e40fdc71
