# {% set stack_name = "nextflow-tower-config" %}
template_path: nextflow-tower-config-bucket.yaml
stack_name: {{ stack_name }}
parameters:
  BucketName: {{ stack_name }}
hooks:
  after_launch:
    - !cmd "aws s3 cp tower-config/ s3://{{ stack_name }}/ --recursive"
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
