template_path: nextflow-aurora-mysql.yaml
stack_name: nextflow-aurora-mysql
dependencies:
  - prod/nextflow-vpc.yaml
parameters:
  VpcID: !stack_output_external nextflow-vpc::VPCId
  SubnetIDs:
    - !stack_output_external nextflow-vpc::PrivateSubnet1
    - !stack_output_external nextflow-vpc::PrivateSubnet2
