template_path: nextflow-ecs-security-group.yaml
stack_name: nextflow-ecs-security-group
dependencies:
  - prod/nextflow-vpc.yaml
parameters:
  VpcId: !stack_output_external nextflow-vpc::VPCId
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
