template:
  type: http
  url: "{{stack_group_config.aws_infra_templates_root_url}}/v0.2.20/templates/R53-hostedzone.yaml"
stack_name: nextflow-r53-hostedzone

parameters:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
  DnsDomainName: tower.sagebionetworks.org

stack_tags:
  {{stack_group_config.default_stack_tags}}
