template_path: remote/peer-single-route.yaml
stack_name: peer-nextflowprod-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-02a46bacc9ff24a26
  VpcRouteTable: rtb-01a97ddae43f465be
  VpnCidr: 10.1.0.0/16
hooks:
  before_launch:
    - !cmd "mkdir -p templates/remote/"
    - !cmd "wget {{stack_group_config.aws_infra_templates_root_url}}/v0.2.5/templates/peer-single-route.yaml -O templates/remote/peer-single-route.yaml"
