# Technically, this AWS account isn't set up through SSO since
# it sits outside of our AWS Organization fo STRIDES billing
sso_admin_role:
  arn: arn:aws:iam::751556145034:role/strides-ampad-workflows-admin
