template_path: budget.yaml
stack_name: budget-other
parameters:
  budgetName: budget-other
  emailAddress: "{{stack_group_config.notifications_email}}"
  budgetAmount: "500"
  serviceFilters:
    {{stack_group_config.services.other}}
