template_path: budget.yaml
stack_name: budget-storage
parameters:
  budgetName: budget-storage
  emailAddress: "{{stack_group_config.notifications_email}}"
  budgetAmount: "2000"
  serviceFilters:
    {{stack_group_config.services.storage}}
