template_path: budget.yaml
stack_name: budget-compute
parameters:
  budgetName: budget-compute
  emailAddress: "{{stack_group_config.notifications_email}}"
  budgetAmount: "5000"
  serviceFilters:
    {{stack_group_config.services.compute}}
