template_path: smtp-credentials.yaml
stack_name: smtp-credentials
parameters:
  IamAccessKeyVersion: '1'
  TemplateRootUrl: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com'
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
