# Provision a service account for AWS API access keys
template_path: "remote/service-user.yaml"
stack_name: "bgrande-nextflow-service-user"
stack_tags:
  Department: "CompOnc"
  Project: "imCORE"
  OwnerEmail: "bruno.grande@sagebase.org"
parameters:
  ManagedPolicyArns: ["arn:aws:iam::aws:policy/AmazonS3FullAccess"]
hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_templates_root_url}}/v0.2.7/templates/IAM/service-user.yaml -N -P templates/remote"
