template_path: nextflow-ecs-cluster.yaml
stack_name: nextflow-ecs-cluster
dependencies:
  - develop/nextflow-vpc.yaml
  - develop/nextflow-ecs-security-group.yaml
parameters:
  EcsSecurityGroupId: !stack_output_external nextflow-ecs-security-group::SecurityGroupId
  SubnetId: !stack_output_external nextflow-vpc::PrivateSubnet
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
