template_path: remote/vpc-20-private.yaml
stack_name: nextflow-vpc
parameters:
  VpcName: nextflow-vpc
  VpcSubnetPrefix: "172.21"
hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_templates_root_url}}/v0.2.4/templates/VPC/vpc-20-private.yaml -N -P templates/remote"
