template_path: remote/gateway-vpc-endpoint.yaml
stack_name: nextflow-s3-vpc-endpoint
dependencies:
  - develop/nextflow-vpc.yaml

parameters:
  VpcName: "nextflow-vpc"
  ServiceName: "com.amazonaws.us-east-1.s3"

stack_tags:
  {{stack_group_config.default_stack_tags}}

hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_templates_root_url}}/v0.3.2/templates/gateway-vpc-endpoint.yaml -O templates/remote/gateway-vpc-endpoint.yaml"
