template_path: nextflow-ecs-cluster.j2
stack_name: nextflow-ecs-cluster
dependencies:
  - develop/nextflow-vpc.yaml
  - develop/nextflow-ecs-security-group.yaml
parameters:
  EcsSecurityGroupId: !stack_output_external nextflow-ecs-security-group::SecurityGroupId
  SubnetIds:
    - !stack_output_external nextflow-vpc::PrivateSubnet
  EfsFileSystemId: !stack_output_external nextflow-efs-file-system::FileSystemId
sceptre_user_data:
  TowerConfigFileContents: |
    tower:
      auth:
        github:
          allow-list:
            - tess.thyer@sagebionetworks.org
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
