template_path: nextflow-ecs-cluster.yaml
stack_name: nextflow-ecs-cluster
dependencies:
  - develop/nextflow-vpc.yaml
parameters:
  VpcId: !stack_output_external nextflow-vpc::VPCId
  SubnetIds:
    - !stack_output_external nextflow-vpc::PrivateSubnet
    - !stack_output_external nextflow-vpc::PrivateSubnet1
    - !stack_output_external nextflow-vpc::PrivateSubnet2
  SecurityIngressFromPort: '80'
  SecurityIngressToPort: '8080'
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
