template_path: nextflow-ecs-capacity.yaml
stack_name: nextflow-ecs-capacity
dependencies:
  - develop/nextflow-ecs-cluster.yaml
parameters:
  EcsClusterName: !stack_output_external nextflow-ecs-cluster::EcsClusterName
  AutoScalingGroupArn: !rcmd >-
    aws autoscaling describe-auto-scaling-groups
    | jq -r '.AutoScalingGroups | .[] | select(.AutoScalingGroupName | startswith("nextflow-ecs-cluster-EcsAutoScalingGroup")) | .AutoScalingGroupARN'
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
