# {% set stack_name = "nextflow-tower-config-dev" %}
template_path: nextflow-tower-config-bucket.yaml
stack_name: {{ stack_name }}

parameters:
  BucketName: {{ stack_name }}

stack_tags:
  {{stack_group_config.default_stack_tags}}

hooks:
  after_launch:
    - !cmd "aws s3 cp tower-config/ s3://{{ stack_name }}/ --recursive"
