template_path: nextflow-ecs-cluster.yaml
stack_name: nextflow-ecs-cluster
dependencies:
  - develop/nextflow-vpc.yaml
parameters:
  EcsSecurityGroupId: !stack_output_external nextflow-ecs-security-group::SecurityGroupId
  SubnetIds:
    - !stack_output_external nextflow-vpc::PublicSubnet
  # SecurityIngressFromPort: '80'
  # SecurityIngressToPort: '8080'
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
