template_path: nextflow-efs-file-system.yaml
stack_name: nextflow-efs-file-system
dependencies:
  - develop/nextflow-vpc.yaml
  - develop/nextflow-ecs-security-group.yaml
  - develop/nextflow-tower-config-bucket.yaml
parameters:
  VpcId: !stack_output_external nextflow-vpc::VPCId
  SubnetId: !stack_output_external nextflow-vpc::PublicSubnet
  EcsSecurityGroupId: !stack_output_external nextflow-ecs-security-group::SecurityGroupId
  NextflowTowerConfigBucketArn: !stack_output_external nextflow-tower-config-bucket::BucketArn
stack_tags:
  Department: IBC
  Project: Infrastructure
  OwnerEmail: nextflow-admins@sagebase.org
