template_path: remote/vpc-20-private.yaml
stack_name: nextflow-vpc

parameters:
  VpcName: nextflow-vpc
  VpcSubnetPrefix: "172.21"

stack_tags:
  {{stack_group_config.default_stack_tags}}

hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_templates_root_url}}/v0.3.0/templates/VPC/vpc-20-private.yaml -O templates/remote/vpc-20-private.yaml"
