template:
  type: http
  url: "{{stack_group_config.aws_infra_templates_root_url}}/v0.2.3/templates/S3/public-bucket.yaml"
stack_name: "cloudformation-templates"
stack_tags:
  Department: "CompOnc"
  Project: "imCORE"
  OwnerEmail: "bruno.grande@sagebase.org"
