AWSTemplateFormatVersion: 2010-09-09

Description: Nextflow tower jwt and crypto secrets

Parameters:

  KmsKeyAlias:
    Description: Optional. KMS key alias used to encrypt secrets stored in Secrets Manager.
    Type: String
    Default: 'alias/workflows-infra'

Resources:

  JwtSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/jwt'
      Description: 'JWT secret for Nextflow Tower'
      GenerateSecretString:
        PasswordLength: 70
        SecretStringTemplate: '{}'
        GenerateStringKey: secret
      KmsKeyId: !Ref KmsKeyAlias

  CryptoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}/crypto'
      Description: 'Crypto secret for Nextflow Tower'
      GenerateSecretString:
        PasswordLength: 70
        SecretStringTemplate: '{}'
        GenerateStringKey: secret
      KmsKeyId: !Ref KmsKeyAlias
