AWSTemplateFormatVersion: 2010-09-09

Description: ECS Cluster Capacity Provider

Parameters:

  AutoScalingGroupArn:
    Type: String
    Description: >
      The ARN of the autoscaling group that will be used
      as a capacity provider to an ECS cluster.

  EcsClusterName:
    Type: String
    Description: The ECS cluster to associate with the capacity provider.

Resources:

  EcsCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref AutoScalingGroupArn

  EcsClusterCapacityProviderAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      CapacityProviders:
        - !Ref EcsCapacityProvider
      Cluster: !Ref EcsClusterName
      DefaultCapacityProviderStrategy:
        - CapacityProvider: !Ref EcsCapacityProvider

Outputs:

  EcsCapacityProviderName:
    Value: !Ref EcsCapacityProvider
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-EcsCapacityProviderName'
