AWSTemplateFormatVersion: '2010-09-09'
Description: Nextflow Tower ECS Task Definition template
Parameters:
  TowerSmtpHost:
    Type: String
    Description: SMTP server hostname
  TowerSmtpPort:
    Type: String
    Description: SMTP server port
  TowerSmtpUser:
    Type: String
    Description: SMTP server username
    NoEcho: 'true'
  TowerSmtpPassword:
    Type: String
    Description: SMTP server password
    NoEcho: 'true'
  TowerContactEmail:
    Type: String
    Description: Email for login emails
  TowerServerUrl:
    Type: String
    Description: IP address of container instance
  TowerJwtSecret:
    Type: String
    Description: '>256 bit random string'
    NoEcho: 'true'
  TowerCryptoSecretkey:
    Type: String
    Description: '>256 bit random string'
    NoEcho: 'true'
  TowerLicense:
    Type: String
    Description: The Tower License
    NoEcho: 'true'
  TowerDbUrl:
    Type: String
    Description: MySQL DB connection URL
  TowerDbUser:
    Type: String
    Description: MySQL DB username
  TowerDbPassword:
    Type: String
    Description: MySQL DB password
    NoEcho: 'true'
  TowerGithubClientId:
    Type: String
    Description: The client id provided by GitHub for the OAuth app
    NoEcho: 'true'
  TowerGithubSecret:
    Type: String
    Description: The client secret provided by GitHub for the OAuth app
    NoEcho: 'true'
  RedisContainerName:
    Type: String
    Description: (Optional) Name of the container that runs redis
    Default: redis
  RedisContainerImage:
    Type: String
    Description: (Optional) Redis container docker image
    Default: 'redis:5.0.8'
  CronContainerName:
    Type: String
    Description: (Optional) Name of the cron container
    Default: cron
  CronContainerImage:
    Type: String
    Description: (Optional) Cron container docker image
    Default: '195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower-enterprise/backend:v21.06.0'
  FrontendContainerName:
    Type: String
    Description: (Optional) Name of the container that runs the tower ui
    Default: frontend
  FrontendContainerImage:
    Type: String
    Description: (Optional) Frontend container docker image
    Default: '195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower-enterprise/frontend:v21.06.0'
  FrontendContainerPort:
    Type: Number
    Description: (Optional) Port to open in frontend container
    Default: 80
  FrontendHostPort:
    Type: Number
    Description: (Optional) Port to open on host for frontend container
    Default: 80
  BackendContainerName:
    Type: String
    Description: (Optional) Name of the container that runs the tower server
    Default: backend
  BackendContainerImage:
    Type: String
    Description: (Optional) Backend container docker image
    Default: '195996028523.dkr.ecr.eu-west-1.amazonaws.com/nf-tower-enterprise/backend:v21.06.0'
  BackendContainerPort:
    Type: Number
    Description: (Optional) Port to open in backend container
    Default: 8080
  BackendHostPort:
    Type: Number
    Description: (Optional) Port to open on host for backend container
    Default: 8080
Resources:
  TowerTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: bridge
      Volumes:
        - Name: tower_yaml
          Host:
            SourcePath: '/opt/nextflow/tower.yml'
      ContainerDefinitions:
        - Name: !Ref RedisContainerName
          Image: !Ref RedisContainerImage
          Memory: 2000
          Cpu: 0
          PortMappings:
            - ContainerPort: 6379
              HostPort: 6379
          Command:
            - --appendonly yes
        - Name: !Ref CronContainerName
          Image: !Ref CronContainerImage
          Memory: 2000
          Cpu: 0
          Links:
            - !Ref RedisContainerName
          DependsOn:
            - ContainerName: !Ref RedisContainerName
              Condition: START
          WorkingDirectory: /work
          EntryPoint:
            - /bin/sh
          Command:
            - -c
            - /migrate-db.sh; /tower.sh
          Environment:
            - Name: TOWER_CONTACT_EMAIL
              Value: !Ref 'TowerContactEmail'
            - Name: TOWER_SMTP_HOST
              Value: !Ref 'TowerSmtpHost'
            - Name: TOWER_SMTP_PORT
              Value: !Ref 'TowerSmtpPort'
            - Name: TOWER_SMTP_USER
              Value: !Ref 'TowerSmtpUser'
            - Name: TOWER_SMTP_PASSWORD
              Value: !Ref 'TowerSmtpPassword'
            - Name: TOWER_DB_URL
              Value: !Ref 'TowerDbUrl'
            - Name: TOWER_DB_DRIVER
              Value: com.mysql.cj.jdbc.Driver
            - Name: TOWER_DB_DIALECT
              Value: io.seqera.util.MySQL55DialectCollateBin
            - Name: TOWER_DB_USER
              Value: !Ref 'TowerDbUser'
            - Name: TOWER_DB_PASSWORD
              Value: !Ref 'TowerDbPassword'
            - Name: TOWER_SERVER_URL
              Value: !Ref 'TowerServerUrl'
            - Name: MICRONAUT_ENVIRONMENTS
              Value: prod,redis,cron,awsbatch-platform,auth-github
            - Name: TOWER_JWT_SECRET
              Value: !Ref 'TowerJwtSecret'
            - Name: TOWER_CRYPTO_SECRETKEY
              Value: !Ref 'TowerCryptoSecretkey'
            - Name: TOWER_LICENSE
              Value: !Ref 'TowerLicense'
            - Name: FLYWAY_LOCATIONS
              Value: classpath:db-schema/mysql
            - Name: TOWER_GITHUB_CLIENT
              Value: !Ref TowerGithubClientId
            - Name: TOWER_GITHUB_SECRET
              Value: !Ref TowerGithubSecret
        - Name: !Ref FrontendContainerName
          Image: !Ref FrontendContainerImage
          Memory: 2000
          Cpu: 0
          Essential: false
          PortMappings:
            - ContainerPort: !Ref FrontendContainerPort
              HostPort: !Ref FrontendHostPort
          Links:
            - !Ref BackendContainerName
          DependsOn:
            - ContainerName: !Ref BackendContainerName
              Condition: START
        - Name: !Ref BackendContainerName
          Hostname: !Ref BackendContainerName
          Memory: 2000
          Cpu: 0
          Image: !Ref BackendContainerImage
          PortMappings:
            - ContainerPort: !Ref BackendContainerPort
              HostPort: !Ref BackendHostPort
          Essential: false
          Links:
            - redis
            - cron
          WorkingDirectory: /work
          DependsOn:
            - ContainerName: cron
              Condition: START
            - ContainerName: redis
              Condition: START
          Environment:
            - Name: TOWER_CONTACT_EMAIL
              Value: !Ref 'TowerContactEmail'
            - Name: TOWER_SMTP_HOST
              Value: !Ref 'TowerSmtpHost'
            - Name: TOWER_SMTP_PORT
              Value: !Ref 'TowerSmtpPort'
            - Name: TOWER_SMTP_USER
              Value: !Ref 'TowerSmtpUser'
            - Name: TOWER_SMTP_PASSWORD
              Value: !Ref 'TowerSmtpPassword'
            - Name: TOWER_DB_URL
              Value: !Ref 'TowerDbUrl'
            - Name: TOWER_DB_DRIVER
              Value: com.mysql.cj.jdbc.Driver
            - Name: TOWER_DB_DIALECT
              Value: io.seqera.util.MySQL55DialectCollateBin
            - Name: TOWER_DB_USER
              Value: !Ref 'TowerDbUser'
            - Name: TOWER_DB_PASSWORD
              Value: !Ref 'TowerDbPassword'
            - Name: TOWER_SERVER_URL
              Value: !Ref 'TowerServerUrl'
            - Name: MICRONAUT_ENVIRONMENTS
              Value: prod,redis,ha,awsbatch-platform,auth-github
            - Name: TOWER_JWT_SECRET
              Value: !Ref 'TowerJwtSecret'
            - Name: TOWER_CRYPTO_SECRETKEY
              Value: !Ref 'TowerCryptoSecretkey'
            - Name: TOWER_LICENSE
              Value: !Ref 'TowerLicense'
            - Name: FLYWAY_LOCATIONS
              Value: classpath:db-schema/mysql
            - Name: TOWER_GITHUB_CLIENT
              Value: !Ref TowerGithubClientId
            - Name: TOWER_GITHUB_SECRET
              Value: !Ref TowerGithubSecret
          EntryPoint:
            - /bin/sh
          Command:
            - -c
            - /tower.sh
          MountPoints:
            - ContainerPath: '/tower.yml'
              ReadOnly: true
              SourceVolume: tower_yaml

Outputs:

  TaskDefinitionArn:
    Value: !Ref TowerTask
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-TaskDefinitionArn'

  FrontendContainerName:
    Value: !Ref FrontendContainerName
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-FrontendContainerName'

  FrontendContainerPort:
    Value: !Ref FrontendContainerPort
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-FrontendContainerPort'
