AWSTemplateFormatVersion: 2010-09-09
Description: An S3 bucket readable by the account only

Parameters:

  BucketName:
    Type: String
    Description: Name of the created bucket.

  AdminArns:
    Type: CommaDelimitedList
    Description: IAM ARNs that may administer and write to teh bucket
    ConstraintDescription: >
      List of ARNs (i.e. ['arn:aws:iam::011223344556:user/jsmith',
      'arn:aws:iam::544332211006:user/rjones']

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: FullAccess
            Effect: Allow
            Principal:
              AWS: !Ref AdminArns
            Action: 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${Bucket}'
              - !Sub 'arn:aws:s3:::${Bucket}/*'
          - Sid: 'AllowRead'
            Effect: 'Allow'
            Principal:
              AWS: !Sub '${AWS::AccountId}'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'

Outputs:

  BucketName:
    Value: !Ref Bucket
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BucketName'

  BucketArn:
    Value: !GetAtt Bucket.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BucketArn'
