AWSTemplateFormatVersion: '2010-09-09'

Description: KMS key for workflows infrastructure

Parameters:
  TemplateRootUrl:
    Type: String
    Description: URL of S3 bucket where templates are deployed
    ConstraintDescription: Must be a valid S3 HTTP URL

  AccountAdminArns:
    Type: List<String>
    Description: List of admin IAM user and role ARNs (strings)

Resources:

  WorkflowsKeyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${TemplateRootUrl}/aws-infra/v0.2.19/KMS/kms-key.yaml
      TimeoutInMinutes: 5
      Parameters:
        AliasName: 'alias/workflows-infra'
        AdminPrincipalArns: !Join
          - ','
          - - !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            - !ImportValue
              'Fn::Sub': '${AWS::Region}-workflows-nextflow-ci-service-account-ServiceRoleArn'
            - !Join [",", !Ref AccountAdminArns]
        UserPrincipalArns: !Join
          - ','
          - - !ImportValue
              'Fn::Sub': '${AWS::Region}-workflows-nextflow-ci-service-account-ServiceRoleArn'
            - !Join [",", !Ref AccountAdminArns]

Outputs:
  Key:
    Value: !Sub ${WorkflowsKeyStack.Outputs.Key}
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-Key'
  Alias:
    Value: !Sub ${WorkflowsKeyStack.Outputs.Alias}
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-Alias'
  KeyArn:
    Value: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${WorkflowsKeyStack.Outputs.Key}'
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-KeyArn'
