name: aws-deploy

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  pre-commit:
    name: Run pre-commit hooks against all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.2

  sceptre-deploy:
    name: Deploy CloudFormation templates using sceptre
    runs-on: ubuntu-latest
    needs: pre-commit
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create directory for remote sceptre templates
        run: mkdir -p templates/remote/

      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: python -m pip install pipenv

      - name: Set up dependency caching
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-v2-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-v2-

      - name: Install dependencies
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        env:
          PIPENV_NOSPIN: 'true'
          WORKON_HOME: ~/.local/share/virtualenvs
          PIPENV_CACHE_DIR: ~/.local/share/pipcache
        run: |
          pipenv install --dev

      - name: Assume AWS role in dev account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NEXTFLOW_DEV_CI_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.NEXTFLOW_DEV_CI_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::035458030717:role/workflows-nextflow-ci-service-account-ServiceRole-188LV3KMGCYBL
          role-duration-seconds: 3600

      - name: Deploy common configuration to develop account
        run: pipenv run sceptre launch common --yes

      - name: Deploy develop configuration
        run: pipenv run sceptre launch develop --yes

      - name: Deploy projects-dev configuration
        run: pipenv run sceptre launch projects-dev --yes

      - name: Wait for tower-dev to be up
        uses: nev7n/wait_for_response@v1
        with:
          url: https://tower-dev.sagebionetworks.org/
          responseCode: 200
          timeout: 180000
          interval: 10000

      - name: Configure projects-dev in Tower
        run: pipenv run bin/configure-tower-projects.py config/projects-dev/
        env:
          NXF_TOWER_TOKEN: ${{ secrets.TOWER_DEV_TOKEN }}

      - name: Assume AWS role in prod account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NEXTFLOW_PROD_CI_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.NEXTFLOW_PROD_CI_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::728882028485:role/workflows-nextflow-ci-service-account-ServiceRole-CTLXKJIOCRO4
          role-duration-seconds: 3600

      - name: Deploy common configuration to prod account
        run: pipenv run sceptre launch common --yes

      - name: Deploy prod configuration
        run: pipenv run sceptre launch prod --yes

      - name: Deploy projects configuration
        run: pipenv run sceptre launch projects --yes

      - name: Wait for tower-prod to be up
        uses: nev7n/wait_for_response@v1
        with:
          url: https://tower.sagebionetworks.org/
          responseCode: 200
          timeout: 180000
          interval: 30000

      - name: Configure projects in Tower
        run: pipenv run bin/configure-tower-projects.py config/projects/
        env:
          NXF_TOWER_TOKEN: ${{ secrets.TOWER_PROD_TOKEN }}
